#!/usr/bin/env python3
"""Refresh the port's deterministic Google Play version-code catalog.

Every build Google Play still serves is listed, except 1.26 and newer, whose
PairIP packaging the upstream launcher cannot open at all. Offering a download
that provably cannot install is worse than not offering it, especially over a
handheld's network.

The classification in each row -- edition, named update, renderer, UI size,
warnings -- is NOT decided here. It comes from the Windows helper's catalog
module, so the on-device list and the desktop downloader cannot drift apart:
there is one implementation of "is this RenderDragon", and both read its answer.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HELPER = ROOT / "tools" / "mcbedrock-get"
sys.path.insert(0, str(HELPER))

import catalog  # noqa: E402  (path set above)

OUTPUT = (
    ROOT
    / "portmaster/minecraftbedrock/minecraftbedrock/downloader/version_catalog.tsv"
)

# 1.26 replaced the packaging with PairIP, which the launcher cannot load.
UNRUNNABLE_FROM = "1.26"

# This port ships a modern mcpelauncher-manifest client. Everything at or above
# this line is inside the range the port has evidence for; below it the client
# is untested here, whatever the build itself is capable of. The rows are still
# offered -- the user asked for the full list -- but they say so.
TESTED_FROM = "1.16"

COLUMNS = (
    "version_code", "abi", "channel", "version_name",
    "edition", "update", "renderer", "ui", "notes",
)


def catalogued(release: catalog.Release, abi: str) -> tuple[str, ...]:
    """One row: the four original columns, then what the build actually is."""
    notes = release.advice(abi)
    if catalog.version_key(release.name) < catalog.version_key(TESTED_FROM):
        older = "older than any build tested on this port"
        notes = f"{notes} · {older}" if notes else older
    return (
        str(release.code_for(abi)),
        abi,
        "preview" if release.beta else "release",
        release.name,
        release.edition,
        release.update_name,
        release.renderer_label(abi),
        "Tiny UI" if release.tiny_ui else "",
        notes,
    )


def main() -> int:
    available = catalog.load(force_refresh=True, on_status=lambda line: print(line))
    if not available.complete:
        print("refusing to write a catalog built from the offline fallback", file=sys.stderr)
        return 1

    cutoff = catalog.version_key(UNRUNNABLE_FROM)
    rows: list[tuple[str, ...]] = []
    skipped = 0
    for release in available.releases:
        if catalog.version_key(release.name) >= cutoff:
            skipped += 1
            continue
        for abi in ("arm64", "armhf"):
            if release.supports(abi):
                rows.append(catalogued(release, abi))

    # Grouped the way the on-device menu pages through them: architecture, then
    # channel, then newest first.
    rows.sort(
        key=lambda row: (
            row[1],
            row[2],
            [-part for part in catalog.version_key(row[3])[0]],
            row[0],
        )
    )

    lines = [
        "# Generated by scripts/update_gplay_version_catalog.py",
        "# Sources: minecraft-linux/mcpelauncher-versiondb architecture databases",
        "# Classification: tools/mcbedrock-get/catalog.py (shared with the Windows helper)",
        "# " + "\t".join(COLUMNS),
    ]
    lines += ["\t".join(row) for row in rows]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} version/architecture entries to {OUTPUT}")
    print(f"excluded {skipped} builds from {UNRUNNABLE_FROM} and newer (PairIP)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
