#!/usr/bin/env bash
# Cross-compile bottomd (wayland backend) for the RG DS (aarch64) using
# the mcpe-build:bookworm Docker image.
#
# Deps prepared once (see BOTTOMSCREEN_HANDOFF.md):
# - wl_include/ : vendored wayland-client headers (arch-independent,
#   copied from WSL's libwayland-dev)
# - xdg-shell-{client-protocol.h,protocol.c} : generated by
#   wayland-scanner from wayland-protocols' xdg-shell.xml
# - /root/bedrockmap/devlibs/libwayland-client.so.0 : pulled from the
#   RG DS itself (ROCKNIX libwayland 1.23) — we link directly against
#   the device's library.
#
# Run from WSL: bash build_arm64_wsl.sh
set -e
SRC=/mnt/c/Programmering/SBC/RG34xxSP/Minecraft_Bedrock_PortMaster/bottomscreen
OUT=/root/bedrockmap

# xdg-shell-{client-protocol.h,protocol.c} are GENERATED and not in the
# repo — and `make clean` deletes them (they are in WAYLAND_GEN). Without
# this the docker build dies on a missing file, which reads like a broken
# cross-compiler rather than a missing codegen step. Regenerate if absent.
XDG_XML=${XDG_SHELL_XML:-/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml}
if [ ! -f "$SRC/bottomd/xdg-shell-protocol.c" ] ||
   [ ! -f "$SRC/bottomd/xdg-shell-client-protocol.h" ]; then
  echo "== regenerating xdg-shell protocol sources =="
  wayland-scanner client-header "$XDG_XML" \
      "$SRC/bottomd/xdg-shell-client-protocol.h"
  wayland-scanner private-code "$XDG_XML" \
      "$SRC/bottomd/xdg-shell-protocol.c"
fi
docker run --rm \
  -v "$SRC":/bs:ro \
  -v /root/bedrockmap:/out \
  mcpe-build:bookworm bash -c '
set -e
S=/bs/bottomd
clang --target=aarch64-linux-gnu -O2 -Wall -Wextra -std=c11 \
  -DBOTTOMD_HAVE_WAYLAND -I$S/wl_include -I$S \
  -o /out/bottomd.arm64 \
  $S/bottomd.c $S/companion.c $S/draw.c $S/gamepad.c $S/keyfwd.c \
  $S/pages.c $S/paneltouch.c $S/screenflip.c $S/texture.c $S/tiles.c \
  $S/touchfwd.c $S/worldinfo.c \
  $S/backend_ppm.c $S/backend_fbdev.c $S/backend_wayland.c \
  $S/xdg-shell-protocol.c \
  /out/devlibs/libwayland-client.so.0 -lrt -lm -lpng \
  -Wl,--allow-shlib-undefined
file /out/bottomd.arm64'
# --allow-shlib-undefined: the DEVICE libwayland references glibc-2.38
# __isoc23_* symbols missing from the bookworm cross sysroot; they
# resolve at runtime on ROCKNIX (glibc 2.41). bottomd itself only needs
# <=2.36 symbols.
echo "built $OUT/bottomd.arm64"
